name: Build RCONLib
on:
  - push
jobs:
  build:
    strategy:
      matrix:
        java:
          - 11
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Make Gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
      - name: Upload build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '11' }}
        uses: actions/upload-artifact@v2
        with:
          name: RCONLib
          path: build/libs/*.jar
      - name: Publish to GitHub Packages
        env:
          ACTOR: "RTAkland"
          TOKEN: ${{ secrets.GIT_TOKEN }}
        run: ./gradlew publish